openapi: 3.2.0
info:
  title: Engine by MoneyLion Approval Probability API
  version: 1.106.0
  termsOfService: https://engine.tech/about/legal#terms
  contact:
    name: API Support
    url: https://engine.tech/docs
    email: help@engine.tech
  description: Approval probability reports contains data about the likelihood that a user with specified attributes will be approved for particular product offers.
servers:
- url: https://api.engine.tech
tags:
- name: Approval Probability
  description: Approval probability reports contains data about the likelihood that a user with specified attributes will be approved for particular product offers.
paths:
  /approvalProbability/loanReports:
    post:
      x-implemented-by:
        service: approval-probability
        path: /approvalProbability/loanReports
      summary: Get a loan approval probability report
      description: Get a report on approval probabilities for loan offers for a specified cohort of users.
      operationId: createLoansApprovalProbabilityReport
      security:
      - experimentalBearerToken: []
      tags:
      - Approval Probability
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanReportCreateData'
            examples:
              loanApprovalProbabilityCreateData:
                $ref: '#/components/examples/LoanApprovalProbabilityCreateData'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanReport'
              examples:
                loanApprovalProbabilityReport:
                  $ref: '#/components/examples/LoanApprovalProbabilityReport'
        '400':
          $ref: '#/components/responses/MalformedRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedRequest'
        '422':
          $ref: '#/components/responses/InvalidRequest'
  /approvalProbability/loanReports/{uuid}:
    parameters:
    - name: uuid
      in: path
      required: true
      schema:
        type: string
        format: uuid
    get:
      x-implemented-by:
        service: approval-probability
        path: /approvalProbability/loanReports/{uuid}
      summary: Get approval probability loan report
      description: Get the approval probability report for a specified UUID. If the UUID is unkown, a `404 Not Found` response will be returned.
      operationId: getLoansApprovalProbabilityReport
      security:
      - experimentalBearerToken: []
      tags:
      - Approval Probability
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanReport'
              examples:
                loanApprovalProbabilityReport:
                  $ref: '#/components/examples/LoanApprovalProbabilityReport'
        '400':
          description: Malformed request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiError'
              examples:
                invalidUuidPathParameter:
                  $ref: '#/components/examples/InvalidUuidPathParameter'
        '401':
          $ref: '#/components/responses/UnauthorizedRequest'
        '404':
          description: Unknown UUID
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiError'
components:
  responses:
    MalformedRequest:
      description: Malformed request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiError'
          examples:
            invalidUuidPathParameter:
              $ref: '#/components/examples/InvalidUuidPathParameter'
    InvalidRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiError'
    UnauthorizedRequest:
      description: Unauthorized request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ApiError'
          examples:
            missingAccessToken:
              summary: Access token was not specified
              value:
              - message: Access token is missing
  schemas:
    ApiError:
      type: object
      properties:
        attribute:
          type: string
          description: 'The attribute that this error applies to. Omitted if this error is not in the context of a resource, or cannot be isolated to a single attribute.

            '
        type:
          type: string
          description: 'A classification for this error, which can be used to render the appropriate custom error template, or take other programmatic actions.

            '
        details:
          description: 'Variables associated with this error that can be injected into a custom error template, or used to parameterize any other programatic actions.

            '
          allOf:
          - $ref: '#/components/schemas/ApiErrorDetails'
        message:
          type: string
          description: 'A human-readable, English description of the error.

            '
    State:
      type: string
      format: state
      title: state
      description: A two character upper case state, Puerto Rico, or District of Columbia code
      enum:
      - AK
      - AL
      - AR
      - AZ
      - CA
      - CO
      - CT
      - DC
      - DE
      - FL
      - GA
      - HI
      - IA
      - ID
      - IL
      - IN
      - KS
      - KY
      - LA
      - MA
      - MD
      - ME
      - MI
      - MN
      - MO
      - MS
      - MT
      - NC
      - ND
      - NE
      - NH
      - NJ
      - NM
      - NV
      - NY
      - OH
      - OK
      - OR
      - PA
      - PR
      - RI
      - SC
      - SD
      - TN
      - TX
      - UT
      - VA
      - VI
      - VT
      - WA
      - WI
      - WV
      - WY
    LoanReportCreateData:
      type: object
      required:
      - annualIncome
      - creditRating
      properties:
        annualIncome:
          type: integer
          format: int32
          description: The user's annual income in dollars.
        creditRating:
          description: The user's credit score range.
          allOf:
          - $ref: '#/components/schemas/ProvidedCreditRating'
        totalDebt:
          type: integer
          format: int32
          description: The user's total debt in dollars.
        countOfDerogatories:
          type: integer
          format: int32
          description: The number of derogatory accounts listed on the user's credit report.
        state:
          description: The user's state of residence.
          allOf:
          - $ref: '#/components/schemas/State'
        loanPurpose:
          description: The reason for the loan.
          allOf:
          - $ref: '#/components/schemas/LoanPurpose'
        loanAmount:
          type: integer
          format: int32
          description: The size of the the loan.
    ApiErrorDetails:
      type: object
      additionalProperties:
        type: string
    ProvidedCreditRating:
      type: string
      enum:
      - excellent
      - good
      - fair
      - poor
      - limited
      - unknown
    LoanProbability:
      type: object
      required:
      - probability
      - aprPercentMin
      - aprPercentMax
      - termMonthsMin
      - termMonthsMax
      properties:
        probability:
          type: number
          format: double
          description: The likelihood of approval for loans that match the criteria.
        aprPercentMin:
          type: number
          format: double
          description: The minimum APR for loans with this approval probability.
        aprPercentMax:
          type: number
          format: double
          description: The maximum APR for loans with this approval probability.
        termMonthsMin:
          type: integer
          format: int64
          description: The minimum term length for loans with this approval probability.
        termMonthsMax:
          type: integer
          format: int64
          description: The maximum term length for loans with this approval probability.
        productSubType:
          description: The optional loan sub-type of loans with this approval probability.
          allOf:
          - $ref: '#/components/schemas/ProductSubType'
    LoanReport:
      type: object
      required:
      - uuid
      - annualIncome
      - creditRating
      - networkProbabilities
      - financialInsitutions
      - createdAt
      properties:
        uuid:
          type: string
          format: uuid
          description: A unique identifier for this report.
        annualIncome:
          type: integer
          format: int32
          description: The user's annual income in dollars.
        creditRating:
          description: The user's credit score range.
          allOf:
          - $ref: '#/components/schemas/ProvidedCreditRating'
        totalDebt:
          type: integer
          format: int32
          description: The user's total debt in dollars.
        countOfDerogatories:
          type: integer
          format: int32
          description: The number of derogatory accounts listed on the user's credit report.
        state:
          description: The user's state of residence.
          allOf:
          - $ref: '#/components/schemas/State'
        loanPurpose:
          description: The reason for the loan.
          allOf:
          - $ref: '#/components/schemas/LoanPurpose'
        loanAmount:
          type: integer
          format: int32
          description: The size of the the loan.
        networkProbabilities:
          type: array
          items:
            $ref: '#/components/schemas/LoanProbability'
          description: Probabilities for classes of loans, irrespective of financial institution.
        financialInsitutions:
          type: array
          items:
            $ref: '#/components/schemas/FinancialInstitutionLoanReport'
          description: Probabilities broken out for specific financial institutions.
        createdAt:
          type: string
          format: date-time
          description: When this report was created.
    FinancialInstitutionLoanReport:
      type: object
      required:
      - uuid
      - name
      - probabilities
      properties:
        uuid:
          type: string
          format: uuid
          description: The unique identifier for the financial institution.
        name:
          type: string
          description: The name of the financial institution.
        logoUrl:
          type: string
          description: A URL of a logo for the financial institution.
        probabilities:
          type: array
          items:
            $ref: '#/components/schemas/LoanProbability'
          description: The approval probabilities for the financial intitution.
    ProductSubType:
      type: string
      description: A type of financial product
      enum:
      - credit_card
      - secured_card
      - student_card
      - personal_loan
      - secured_loan
      - student_loan_refinance
      - co_applicant_loan
      - line_of_credit
      - automobile_refinance
      - home_equity_line_of_credit
      - purchase
      - refinance
      - savings_account
      - money_market_account
      - certificate_of_deposit
      - individual_retirement_account
      - cash_management_account
      - high_interest_checking
      - checking
      - accidental_death_benefits
      - term_life
      - term_life_instant
      - whole_life
      - bill_reduction
      - debt_relief
      - installment_loans
      - credit_builder
      - cash_advance
      - credit_repair
      - education_offers
      - employment_opportunity
      - financial_wellness
      - direct_affiliate
      - overdraft_protection
      - revenue_based_financing
      - installment_loan_more_offers
      - credit_card_more_offers
      - credit_repair_more_offers
      - student_loan
      - health
      - auto_and_vehicle
      - games
      - home
      - rewards
      - life_insurance
      - auto_insurance
      - specialty_vehicle_insurance
      - home_owners_insurance
      - renters_insurance
      - uncategorized
      - buy_now_pay_later
      - home_equity_agreements
      - cash_advance_moneylion
      - unknown
    LoanPurpose:
      type: string
      enum:
      - auto
      - auto_purchase
      - auto_refinance
      - baby
      - boat
      - business
      - car_repair
      - cosmetic
      - credit_card_refi
      - debt_consolidation
      - emergency
      - engagement
      - green
      - home_improvement
      - home_purchase
      - home_refi
      - household_expenses
      - large_purchases
      - life_event
      - medical_dental
      - motorcycle
      - moving_relocation
      - other
      - rv
      - special_occasion
      - student_loan
      - student_loan_refi
      - taxes
      - vacation
      - wedding
  examples:
    LoanApprovalProbabilityCreateData:
      summary: Loan approval probability create data
      value:
        annualIncome: 75000
        creditRating: excellent
        totalDebt: 10000
        countOfDerogatories: 0
        state: NY
        loanPurpose: debt_consolidation
        loanAmount: 10000
    LoanApprovalProbabilityReport:
      summary: Loan approval probability report
      value:
        annualIncome: 75000
        creditRating: excellent
        totalDebt: 10000
        countOfDerogatories: 0
        state: NY
        loanPurpose: debt_consolidation
        loanAmount: 10000
        networkProbabilities:
        - probability: 79.67534
          aprLow: 12.76
          aprHigh: 19.85
        financialInsitutions:
        - uuid: 005b235e-9388-5e96-9d43-d1b6fd587652
          name: Alpha, Inc.
          logoUrl: https://aff-tag.evenfinancial.com/images/alpha/Alpha_120x80.png
          probabilities:
          - probability: 49.945
            aprLow: 15.25
            aprHigh: 19.85
        - uuid: c5e7db20-81a4-4fe4-9100-fb8b3ae84f02
          name: Beta Inc.
          logoUrl: https://aff-tag.evenfinancial.com/images/beta/Beta_120x80.png
          probabilities:
          - probability: 84.5421
            aprLow: 12.76
            aprHigh: 18.85
    InvalidUuidPathParameter:
      summary: Invalid UUID in path parameter
      value:
      - message: Bad request.
        details: 'Cannot parse parameter uuid as UUID: Invalid UUID string: 123'
  securitySchemes:
    publishableBearerToken:
      type: http
      scheme: bearer
      description: 'A bearer token that is assumed to be published in application code and downloaded to a user''s device. As a result, it only has restricted access to the API.

        '
    confidentialBearerToken:
      type: http
      scheme: bearer
      description: 'A bearer token that is assumed to be managed like a password or any other confidential secret. As a result, it has access to sensitive API endpoints.

        '
    experimentalBearerToken:
      type: http
      scheme: bearer
      description: 'A bearer token that is used to access experimental endpoints that are not yet available for all partners. It may be treated the same as a `publishableBearerToken`.

        '
externalDocs:
  description: Engine by MoneyLion API Reference
  url: https://engine.tech/docs/api-reference/
